CREATE TABLE ADDRESS
(ADDRESS_ID INTEGER NOT NULL,
FIRST_LINE VARCHAR(60),
AREA VARCHAR(30),
CITY VARCHAR(40),
POST_CODE VARCHAR(10),
CONSTRAINT P_KEY_ADDRESS PRIMARY KEY(ADDRESS_ID));


CREATE TABLE PERSON
(P_ID INTEGER NOT NULL,
NAME VARCHAR(30),
SURNAME CHAR (30),
DOB DATE NOT NULL,
P_EMAIL VARCHAR(40),
P_PHONE_NR VARCHAR(13),
GENDER VARCHAR(20),
PERSON_ADDRESS_ID INTEGER NOT NULL,
CONSTRAINT P_KEY_PERSON PRIMARY KEY(P_ID),
CONSTRAINT FK_PERSON_ADDRESS_ID FOREIGN KEY (PERSON_ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID));


ALTER TABLE PERSON
ADD CONSTRAINT CHECK_GENDER
CHECK (GENDER IN ('MALE', 'FEMALE', 'OTHER'));
CREATE TABLE ESTATE_AGENT
(AGENT_CODE INTEGER NOT NULL,
A_NAME VARCHAR(30) NOT NULL,
HEADQUARTER VARCHAR(60),
A_WEBSITE VARCHAR(40),
A_TEL_NR VARCHAR(15),
A_EMAIL VARCHAR(30),
REG_ADDRESS VARCHAR(60),
CONSTRAINT P_KEY_ESTATE_AGENT PRIMARY KEY(AGENT_CODE));


CREATE TABLE BRANCH
(BRANCH_CODE INTEGER NOT NULL,
B_TEL_NR VARCHAR(13),
B_EMAIL VARCHAR(30),
B_ADDRESS_ID INTEGER NOT NULL,
AGENT_CODE INTEGER NOT NULL,
CONSTRAINT P_KEY_BRANCH PRIMARY KEY(BRANCH_CODE),
CONSTRAINT FK_B_ADDRESS_ID FOREIGN KEY (B_ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID),
CONSTRAINT FK_AGENT_CODE FOREIGN KEY (AGENT_CODE) REFERENCES ESTATE_AGENT(AGENT_CODE));


CREATE TABLE STAFF
(STAFF_ID INTEGER NOT NULL,
SALARY NUMBER(6),
POSITION VARCHAR(20),
START_DATE DATE NOT NULL,
BRANCH_CODE INTEGER NOT NULL,
P_ID INTEGER NOT NULL,
CONSTRAINT P_KEY_STAFF PRIMARY KEY(STAFF_ID),
CONSTRAINT FK_P_ID FOREIGN KEY (P_ID) REFERENCES PERSON(P_ID),
CONSTRAINT FK_BRANCH_CODE FOREIGN KEY (BRANCH_CODE) REFERENCES BRANCH(BRANCH_CODE));



CREATE TABLE MANAGER
(MANAGER_ID INTEGER NOT NULL,
BONUS NUMBER(5),
CONSTRAINT F_KEY_MANAGER_ID FOREIGN KEY(MANAGER_ID) REFERENCES STAFF(STAFF_ID));


CREATE TABLE CLIENT
(CLIENT_ID INTEGER NOT NULL,
C_P_ID INTEGER NOT NULL,
C_TYPE VARCHAR(15),
C_AGENT_CODE INTEGER NOT NULL,
CONSTRAINT P_KEY_CLIENT PRIMARY KEY(CLIENT_ID),
CONSTRAINT FK_C_P_ID FOREIGN KEY(C_P_ID) REFERENCES PERSON(P_ID),
CONSTRAINT FK_C_AGENT_CODE FOREIGN KEY(C_AGENT_CODE) REFERENCES ESTATE_AGENT(AGENT_CODE));


CREATE TABLE RENTER
(RENTER_ID INTEGER NOT NULL,
CONSTRAINT P_KEY_RENTER_ID PRIMARY KEY(RENTER_ID),
CONSTRAINT F_KEY_RENTER_ID FOREIGN KEY(RENTER_ID) REFERENCES CLIENT(CLIENT_ID));


CREATE TABLE BUYER
(BUYER_ID INTEGER NOT NULL,
CONSTRAINT P_KEY_BUYER_ID PRIMARY KEY(BUYER_ID),
CONSTRAINT F_KEY_BUYER_ID FOREIGN KEY(BUYER_ID) REFERENCES CLIENT(CLIENT_ID));

CREATE TABLE LANDLORD
(LANDLORD_ID INTEGER NOT NULL,
CONSTRAINT P_KEY_LANDLORD_ID PRIMARY KEY(LANDLORD_ID),
CONSTRAINT F_KEY_LANDLORD_ID FOREIGN KEY(LANDLORD_ID) REFERENCES CLIENT(CLIENT_ID));


CREATE TABLE PROPERTY
(PROPERTY_ID INTEGER NOT NULL,
TYPE VARCHAR(30),
BRANCH_CODE INTEGER NOT NULL,
DATE_ADDED DATE,
DESCRIBTION VARCHAR(60),
BEDROOM_NR NUMBER(3),
BEDROOM_SIZE VARCHAR(40),
STATUS VARCHAR(30),
LANDLORD_ID INTEGER NOT NULL,
ADDRESS_ID INTEGER NOT NULL,
CONSTRAINT P_KEY_PROPERTY PRIMARY KEY(PROPERTY_ID),
CONSTRAINT F_KEY_BRANCH_CODE FOREIGN KEY(BRANCH_CODE) REFERENCES BRANCH(BRANCH_CODE),
CONSTRAINT F_KEY_ADDRESS_ID FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID));


CREATE TABLE PROPERTY_FOR_RENT
(PROPERTY_FOR_RENT_ID INTEGER NOT NULL,
ASKING_RENT_PCM NUMBER(4),
CONSTRAINT P_KEY_PROPERTY_FOR_RENT_ID PRIMARY KEY(PROPERTY_FOR_RENT_ID),
CONSTRAINT F_KEY_PROPERTY_FOR_RENT_ID FOREIGN KEY(PROPERTY_FOR_RENT_ID) REFERENCES PROPERTY(PROPERTY_ID));


CREATE TABLE PROPERTY_FOR_SALE
(PROPERTY_FOR_SALE_ID INTEGER NOT NULL,
ASKING_PRICE NUMBER(7),

CONSTRAINT P_KEY_PROPERTY_FOR_SALE_ID PRIMARY KEY(PROPERTY_FOR_SALE_ID),
CONSTRAINT F_KEY_PROPERTY_FOR_SALE_ID FOREIGN KEY(PROPERTY_FOR_SALE_ID) REFERENCES PROPERTY(PROPERTY_ID));




CREATE TABLE RENTALS
(PROPERTY_RENTED_ID INTEGER NOT NULL,
RENT_PCM NUMBER(4),
ADVANCE VARCHAR(30),
COMMISSION NUMBER(4),
RENTER_ID INTEGER NOT NULL,
TENANCY_START DATE NOT NULL,
TENANCY_END DATE,
R_STAFF_ID INTEGER NOT NULL,
CONSTRAINT P_KEY_PROPERTY_RENTED_ID PRIMARY KEY(PROPERTY_RENTED_ID),
CONSTRAINT F_KEY_R_STAFF_ID FOREIGN KEY(R_STAFF_ID) REFERENCES STAFF(STAFF_ID),
CONSTRAINT F_KEY_PROPERTY_RENTED_ID FOREIGN KEY(PROPERTY_RENTED_ID) REFERENCES PROPERTY(PROPERTY_ID));




CREATE TABLE SALES
(PROPERTY_SOLD_ID INTEGER NOT NULL,
PRICE_SOLD NUMBER(7),
BUYER_ID INTEGER NOT NULL,
COMMISSION NUMBER(7),
STAMP_DUTY NUMBER(7),
DATE_SOLD DATE,
S_STAFF_ID INTEGER NOT NULL,
CONSTRAINT P_KEY_PROPERTY_SOLD_ID PRIMARY KEY(PROPERTY_SOLD_ID),
CONSTRAINT F_KEY_S_STAFF_ID FOREIGN KEY(S_STAFF_ID) REFERENCES STAFF(STAFF_ID),
CONSTRAINT F_KEY_PROPERTY_SOLD_ID FOREIGN KEY(PROPERTY_SOLD_ID) REFERENCES PROPERTY(PROPERTY_ID));


CREATE TABLE VIEWING
(V_NR INTEGER NOT NULL,
V_DATE DATE,
V_TIME VARCHAR(5),
V_COMMENTS VARCHAR(60),
PROPERTY_ID INTEGER NOT NULL,
CLIENT_ID INTEGER NOT NULL,
V_STAFF_ID INTEGER NOT NULL,
CONSTRAINT P_KEY_V_NR PRIMARY KEY(V_NR),
CONSTRAINT F_KEY_V_STAFF_ID FOREIGN KEY(V_STAFF_ID) REFERENCES STAFF(STAFF_ID),
CONSTRAINT F_KEY_PROPERTY_ID FOREIGN KEY(PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID),
CONSTRAINT F_KEY_CLIENT_ID FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(CLIENT_ID));



ALTER TABLE PROPERTY
ADD CONSTRAINT
FKEY_LANDLORD_ID FOREIGN KEY(LANDLORD_ID) REFERENCES LANDLORD(LANDLORD_ID) DEFERRABLE;

ALTER TABLE RENTALS
ADD CONSTRAINT
FKEY_RENTER_ID FOREIGN KEY(RENTER_ID) REFERENCES RENTER(RENTER_ID) DEFERRABLE;


ALTER TABLE SALES
ADD CONSTRAINT
FKEY_BUYER_ID FOREIGN KEY(BUYER_ID) REFERENCES BUYER(BUYER_ID) DEFERRABLE;
